import React, { useState } from 'react';
import { X, FileText, Sparkles, Download, CheckCircle2, AlertOctagon } from 'lucide-react';

export default function RcaGeneratorModal({ isOpen, onClose, incident }) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [rcaContent, setRcaContent] = useState(`
# ROOT CAUSE ANALYSIS (RCA) & INCIDENT POST-MORTEM BRIEFING
**Incident Reference:** ${incident?.incidentCode || incident?.id || ''}  
**Title:** ${incident?.title || ''}  
**Affected Branch:** ${incident?.branchName || ''}  

---

### Executive Incident Summary
On ${incident?.createdAt ? incident.createdAt.split('T')[0] : '2026-08-15'}, a ${incident?.severity || ''} outage impacted primary branch IT operations at ${incident?.branchName || ''}. Automated monitoring flagged SLA thresholds.

### Primary Root Cause
SNMP diagnostic telemetry indicates hardware power PSU failure triggered by utility voltage drop. Core switch stack failed over to redundant UPS, but battery backup was exhausted after 45 minutes.

### Remediation & Preventative Action Items
1. Replaced failed Cisco Catalyst PSU unit (Tag #PSU-9300-A).
2. Installed dual utility automatic transfer switch (ATS).
3. Scheduled quarterly battery load testing for all branch UPS units.
  `);

  if (!isOpen || !incident) return null;

  const handleDownloadPdf = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/85 backdrop-blur-2xl p-4 modal-backdrop-smooth text-white font-sans text-left">
      <div className="w-full max-w-2xl bg-[#0a0b10]/95 backdrop-blur-2xl border border-white/20 rounded-3xl p-6 sm:p-8 shadow-[0_25px_60px_rgba(0,0,0,0.9)] space-y-5 max-h-[90vh] overflow-y-auto text-white modal-pop-in">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-white/10 pb-4">
          <div className="flex items-center space-x-3">
            <div className="p-2.5 rounded-2xl bg-purple-500/20 text-purple-300 border border-purple-500/30 shadow-glow">
              <Sparkles className="w-6 h-6 text-purple-400" />
            </div>
            <div>
              <h3 className="text-base font-extrabold text-white">AI Automated Root Cause Analysis (RCA)</h3>
              <p className="text-xs text-white/50">Incident post-mortem briefing for regulatory audit compliance</p>
            </div>
          </div>
          <button 
            onClick={onClose}
            className="p-2 rounded-full text-white/50 hover:text-white hover:bg-white/10 transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* RCA Document Box */}
        <div className="p-5 rounded-3xl bg-black/50 border border-white/10 font-mono text-xs leading-relaxed whitespace-pre-line text-white/90 shadow-inner">
          {rcaContent}
        </div>

        <div className="flex items-center justify-between pt-2">
          <span className="text-[11px] text-white/50 font-medium">Generated by BankIT360 AI Engine</span>
          <div className="flex items-center space-x-2">
            <button
              onClick={handleDownloadPdf}
              className="px-5 py-2.5 rounded-full bg-gradient-to-r from-[#ff2d78] to-[#00f5ff] hover:opacity-95 text-white font-extrabold text-xs flex items-center space-x-2 shadow-glow cursor-pointer transition-all"
            >
              <Download className="w-4 h-4" />
              <span>Print / Export PDF</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
